-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ
    START WITH 1 -- 1부터 생성(기본값:1)
    INCREMENT BY 1 -- 1씩 증가(기본값)
    MAXVALUE 9999 -- 최대값
    MINVALUE -9999 -- 최소값
    NOCYCLE
    NOCACHE;      -- 캐시메모리 사용 안함
SELECT FRIEND_SQ.NEXTVAL FROM DUAL; -- DUAL : 오라클 제공 테이블(1행 1열)
SELECT FRIEND_SQ.CURRVAL FROM DUAL; -- CURRVAL(현재까지 진행된 순차번호)

-- EX. 시퀀스를 이용한 FRIEND 테이블 
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO   NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL  VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(255), 
    LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ MAXVALUE 99999 NOCACHE NOCYCLE;

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS) 
    VALUES (FRIEND_SQ.NEXTVAL, '홍길동', NULL, '신림'); -- 여러번실행 가능
SELECT NO, NAME, TEL, ADDRESS, 
    TO_CHAR(LAST_MODIFY, 'RR/MM/DD AM HH:MI:SS') LAST_MODIFY 
    FROM FRIEND;
INSERT INTO FRIEND 
    VALUES (FRIEND_SQ.NEXTVAL, '김길동', '010-9988-9999', '봉천', SYSDATE);

DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ MAXVALUE 9999 NOCACHE NOCYCLE;

DROP TABLE MEMBER_LEVEL;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(1) PRIMARY KEY NOT NULL,
    LEVELNAME VARCHAR2(20) NOT NULL
);

DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    MNO NUMBER(1) PRIMARY KEY NOT NULL,
    MNAME VARCHAR2(20) NOT NULL,
    MPW VARCHAR2(8) NOT NULL,
    MMAIL VARCHAR2(20) UNIQUE,
    MPOINT NUMBER(5) DEFAULT 1000 CHECK(MPOINT>=0),
    MRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(1) REFERENCES MEMBER_LEVEL(LEVELNO)
);
INSERT INTO MEMBER_LEVEL VALUES (-1, 'BLACK');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드');
SELECT * FROM MEMBER_LEVEL;

INSERT INTO MEMBER VALUES (MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'AA', 'HONG@HONG.COM', 0, TO_DATE('24/09/26','RR/DD/MM'),0);
INSERT INTO MEMBER VALUES (MEMBER_MNO_SQ.NEXTVAL, '신길동', 'BB', 'SIN@SIN.COM', 1000, TO_DATE('22/04/01','RR/DD/MM'),1);
SELECT * FROM MEMBER;

SELECT MNO, MNAME, TO_CHAR(MRDATE,'YYYY-MM-DD') MRDATE, MMAIL, MPOINT, LEVELNAME || '고객' LEVELNAME 
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO=L.LEVELNO;












