# Generated by Django 5.2.10 on 2026-01-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="sales",
            field=models.IntegerField(default=1000, verbose_name="판매가"),
        ),
    ]
