# Generated by Django 5.2.10 on 2026-01-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-id"]},
        ),
    ]
